services:
  app:
    build: ./app
    container_name: apprv
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - 8000:8000
    networks:
      - red-ventures
  
  api:
    build: ./api
    container_name: apirv
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - red-ventures

  proxy:
    image: nginx
    build: ./api/proxy
    depends_on:
      - api
      - app
    container_name: nginx
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    networks:
      - red-ventures

networks:
  red-ventures: