services:
  app:
    build: ./app
    container_name: apprv
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - api
    networks:
      - red-ventures
  
  api:
    build: ./api
    container_name: apirv
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - red-ventures

networks:
  red-ventures: